
server:
  port: 8019

spring:
  application:
    name: fileService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i8a703.p.ssafy.io:3306/project1db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: cossafyco
  data:
    web:
      pageable:
        one-indexed-parameters: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 10MB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://i8a703.p.ssafy.io:8761/eureka